import { describe, it, expect } from 'vitest';
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { Agent, createServer, request, type IncomingHttpHeaders, type Server } from 'node:http';
import { connect, type AddressInfo } from 'node:net';
import { CryptoChiefError } from '../src/errors';
import {
  createWebhookHandler,
  parseWebhookEvent,
  signWebhookV1,
  verifyWebhook,
  webhookV1StringToSign,
  WebhookVerificationError,
  WEBHOOK_HEADERS,
  type PayInWebhookEvent,
  type PayoutWebhookEvent,
  type SweepWebhookEvent,
  type TransactionWebhookEvent,
  type WebhookHeaders,
  type WebhookVerificationReason,
  type WebhookVerifyOptions,
} from '../src/webhook';

type Expect = 'ok' | 'bad_headers' | 'timestamp_out_of_range' | 'bad_signature';

interface Vector {
  name: string;
  api_key: string;
  timestamp: number;
  delivery_id: string;
  body?: string;
  body_base64?: string;
  body_sha256: string;
  string_to_sign: string;
  signature: string;
  now: number;
  expect: Expect;
  headers?: Record<string, string[]>;
}

// Generated by processing-webhook-service (internal/signature/testdata/webhook_hmac_v1_vectors.json), copied as is.
const VECTORS_SHA256 = '15a6e1423708e8c3b9ec4fac7ee6eb383db56703605647e02308a29166722502';
const vectorsFile = readFileSync(new URL('./testdata/webhook_hmac_v1_vectors.json', import.meta.url));
const vectors: Vector[] = JSON.parse(vectorsFile.toString('utf8'));

const REASON: Record<Expect, WebhookVerificationReason | undefined> = {
  ok: undefined,
  bad_headers: 'headers',
  timestamp_out_of_range: 'timestamp',
  bad_signature: 'signature',
};

function bodyOf(v: Vector): Buffer {
  if (v.body_base64 !== undefined) return Buffer.from(v.body_base64, 'base64');
  return Buffer.from(v.body!, 'utf8');
}

/** Header lines the receiver sees: defaults, with `headers` replacing the listed names. */
function headerLines(v: Vector): [string, string][] {
  const lines = new Map<string, string[]>([
    [WEBHOOK_HEADERS.timestamp, [String(v.timestamp)]],
    [WEBHOOK_HEADERS.delivery, [v.delivery_id]],
    [WEBHOOK_HEADERS.signature, [v.signature]],
  ]);
  for (const [name, values] of Object.entries(v.headers ?? {})) lines.set(name, values);
  const out: [string, string][] = [];
  for (const [name, values] of lines) for (const value of values) out.push([name, value]);
  return out;
}

function headerRecord(v: Vector): Record<string, string | string[]> {
  const out: Record<string, string | string[]> = {};
  for (const [name, value] of headerLines(v)) {
    const prev = out[name];
    out[name] = prev === undefined ? value : ([] as string[]).concat(prev, value);
  }
  return out;
}

function reasonOf(fn: () => void): WebhookVerificationReason | undefined {
  try {
    fn();
    return undefined;
  } catch (err) {
    if (err instanceof WebhookVerificationError) return err.reason;
    throw err;
  }
}

function atNow(v: Vector): WebhookVerifyOptions {
  return { now: new Date(v.now * 1000), toleranceSec: 300 };
}

function vector(name: string): Vector {
  const v = vectors.find((x) => x.name === name);
  if (!v) throw new Error(`no vector ${name}`);
  return v;
}

describe('webhook HMAC v1 vectors', () => {
  it('has every vector', () => {
    expect(createHash('sha256').update(vectorsFile).digest('hex')).toBe(VECTORS_SHA256);
    const counts: Record<string, number> = {};
    for (const v of vectors) counts[v.expect] = (counts[v.expect] ?? 0) + 1;
    expect(vectors.length).toBe(54);
    expect(counts).toEqual({ ok: 22, bad_headers: 26, bad_signature: 4, timestamp_out_of_range: 2 });
  });

  for (const v of vectors) {
    it(v.name, () => {
      const body = bodyOf(v);
      expect(createHash('sha256').update(body).digest('hex')).toBe(v.body_sha256);

      expect(webhookV1StringToSign(v.timestamp, v.delivery_id, body)).toBe(v.string_to_sign);
      expect(webhookV1StringToSign(BigInt(v.timestamp), v.delivery_id, new Uint8Array(body))).toBe(v.string_to_sign);
      expect(signWebhookV1(v.api_key, v.timestamp, v.delivery_id, body)).toBe(v.signature);
      if (v.body !== undefined) {
        expect(webhookV1StringToSign(v.timestamp, v.delivery_id, v.body)).toBe(v.string_to_sign);
        expect(signWebhookV1(v.api_key, v.timestamp, v.delivery_id, v.body)).toBe(v.signature);
      }

      const want = REASON[v.expect];
      const opts = atNow(v);
      // Record with an array per repeated header.
      expect(reasonOf(() => verifyWebhook(v.api_key, body, headerRecord(v), opts))).toBe(want);
      // [name, value] pairs, one per header line.
      expect(reasonOf(() => verifyWebhook(v.api_key, body, headerLines(v), opts))).toBe(want);
      // Lower-case names, as Node delivers them.
      const lower = headerLines(v).map(([k, x]) => [k.toLowerCase(), x] as [string, string]);
      expect(reasonOf(() => verifyWebhook(v.api_key, body, lower, opts))).toBe(want);
      // Same bytes as a string.
      if (v.body !== undefined) {
        expect(reasonOf(() => verifyWebhook(v.api_key, v.body!, headerRecord(v), opts))).toBe(want);
      }
      // parseWebhookEvent verifies the same way.
      if (want !== undefined) {
        expect(reasonOf(() => parseWebhookEvent(v.api_key, body, headerLines(v), opts))).toBe(want);
      }
      // WHATWG Headers, where values can be represented there.
      if (!headerLines(v).some(([, x]) => /[\r\n]/.test(x))) {
        const h = new Headers();
        for (const [k, x] of headerLines(v)) h.append(k, x);
        expect(reasonOf(() => verifyWebhook(v.api_key, body, h, opts))).toBe(want);
      }
    });
  }
});

describe('verifyWebhook', () => {
  const v = vector('payin_invoice_paid_with_nulls');
  const body = bodyOf(v);
  const headers = headerRecord(v);
  const reason = (h: WebhookHeaders, opts: WebhookVerifyOptions = atNow(v), b: string | Uint8Array = body) =>
    reasonOf(() => verifyWebhook(v.api_key, b, h, opts));

  it('treats two spellings of one header name as a repeat', () => {
    expect(reason({ ...headers, 'x-cc-signature': v.signature })).toBe('headers');
    expect(reason({ ...headers, 'X-CC-TIMESTAMP': String(v.timestamp) })).toBe('headers');
    expect(reason({ ...headers, 'x-webhook-delivery': v.delivery_id })).toBe('headers');
    expect(reason(new Map(Object.entries(headers) as [string, string][]))).toBeUndefined();
  });

  it('matches header names in any case', () => {
    expect(
      reason({
        'X-CC-TIMESTAMP': String(v.timestamp),
        'x-webhook-delivery': v.delivery_id,
        'X-Cc-Signature': v.signature,
      }),
    ).toBeUndefined();
  });

  it('rejects values Node joins for repeated headers', () => {
    expect(reason({ ...headers, 'X-CC-Signature': `${v.signature}, ${v.signature}` })).toBe('headers');
    expect(reason({ ...headers, 'X-CC-Timestamp': `${v.timestamp}, ${v.timestamp}` })).toBe('headers');
  });

  it('ignores the Signature header and needs X-CC-Signature', () => {
    const { 'X-CC-Signature': _sig, ...rest } = headers;
    expect(reason({ ...rest, Signature: v.signature.slice(3) })).toBe('headers');
    expect(reason({ ...headers, Signature: 'deadbeef', 'X-Webhook-Signature': 'deadbeef' })).toBeUndefined();
  });

  it('rejects an absent header record', () => {
    expect(reason({})).toBe('headers');
    expect(reason([])).toBe('headers');
  });

  it('rejects a timestamp with leading zeros', () => {
    for (const ts of ['0' + v.timestamp, '000' + v.timestamp, '00', '01']) {
      expect(reason({ ...headers, 'X-CC-Timestamp': ts })).toBe('headers');
    }
    expect(reason({ ...headers, 'X-CC-Timestamp': String(v.timestamp) })).toBeUndefined();
  });

  it('rejects a timestamp above int64 as headers', () => {
    expect(reason({ ...headers, 'X-CC-Timestamp': '9223372036854775807' })).toBe('timestamp');
    expect(reason({ ...headers, 'X-CC-Timestamp': '9223372036854775808' })).toBe('headers');
    expect(reason({ ...headers, 'X-CC-Timestamp': '99999999999999999999999' })).toBe('headers');
  });

  it('treats timestamp 0 as out of range, and as headers inside the window', () => {
    expect(reason({ ...headers, 'X-CC-Timestamp': '0' })).toBe('timestamp');
    expect(reason({ ...headers, 'X-CC-Timestamp': '0' }, { now: new Date(100_000) })).toBe('headers');
  });

  it('uses toleranceSec, with 300 for zero or less', () => {
    const late = (sec: number) => ({ now: new Date((v.timestamp + sec) * 1000) });
    expect(reason(headers, { ...late(301), toleranceSec: 600 })).toBeUndefined();
    expect(reason(headers, { ...late(601), toleranceSec: 600 })).toBe('timestamp');
    expect(reason(headers, { ...late(300), toleranceSec: 0 })).toBeUndefined();
    expect(reason(headers, { ...late(301), toleranceSec: -5 })).toBe('timestamp');
    expect(reason(headers, { ...late(1), toleranceSec: 0.5 })).toBe('timestamp');
    expect(reason(headers, { ...late(0), toleranceSec: 0.5 })).toBeUndefined();
    expect(reason(headers, late(300))).toBeUndefined();
    expect(reason(headers, late(-300))).toBeUndefined();
    expect(reason(headers, late(-301))).toBe('timestamp');
  });

  it('reads the clock from now, a Date or a function, per call', () => {
    let calls = 0;
    const clock = () => {
      calls++;
      return new Date(v.now * 1000 + 999);
    };
    expect(reason(headers, { now: clock })).toBeUndefined();
    expect(calls).toBe(1);
    expect(reason(headers, {})).toBe('timestamp');
  });

  it('checks headers before the window and the window before the signature', () => {
    const stale = { now: new Date((v.timestamp + 10_000) * 1000) };
    expect(reason({ ...headers, 'X-CC-Signature': 'v1=00' }, stale)).toBe('headers');
    expect(reason({ ...headers, 'X-CC-Signature': 'v1=' + '0'.repeat(64) }, stale)).toBe('timestamp');
    expect(reason({ ...headers, 'X-CC-Signature': 'v1=' + '0'.repeat(64) })).toBe('signature');
  });

  it('rejects one changed body byte', () => {
    const changed = Buffer.from(body);
    changed[changed.length - 2] = changed[changed.length - 2]! ^ 1;
    expect(reason(headers, atNow(v), changed)).toBe('signature');
  });

  it('throws CryptoChiefError, not a verification error, on misuse', () => {
    expect(() => verifyWebhook('', body, headers, atNow(v))).toThrow(CryptoChiefError);
    expect(() => verifyWebhook('', body, headers, atNow(v))).not.toThrow(WebhookVerificationError);
    const parsed = JSON.parse(body.toString('utf8')) as object;
    expect(() => verifyWebhook(v.api_key, parsed as never, headers, atNow(v))).toThrow(
      'raw request body',
    );
    expect(() => verifyWebhook(v.api_key, body, v.signature as never, atNow(v))).toThrow('request headers');
    expect(() => verifyWebhook(v.api_key, body, headers, { now: new Date(NaN) })).toThrow(CryptoChiefError);
    expect(() => verifyWebhook(v.api_key, body, headers, { toleranceSec: Infinity })).toThrow(CryptoChiefError);
  });
});

describe('signWebhookV1', () => {
  it('rejects inputs the sender does not sign', () => {
    const id = '7c9e6679-7425-40de-944b-e07fc1f90ae7';
    for (const ts of [0, -1, 1.5, Number.MAX_SAFE_INTEGER + 1, 0n, 2n ** 63n]) {
      expect(() => signWebhookV1('k', ts, id, '{}')).toThrow(CryptoChiefError);
    }
    for (const bad of ['', 'a'.repeat(129), 'dlv.1', 'dlv\n1', ' dlv']) {
      expect(() => webhookV1StringToSign(1, bad, '{}')).toThrow(CryptoChiefError);
    }
    expect(() => signWebhookV1('', 1, id, '{}')).toThrow(CryptoChiefError);
    expect(signWebhookV1('k', 2n ** 63n - 1n, id, '')).toMatch(/^v1=[0-9a-f]{64}$/);
  });
});

// A key of nothing, or of spaces and tabs only, is no key: signing is an error
// and verification refuses.
describe('blank api key', () => {
  const v = vector('payin_invoice_paid_with_nulls');
  const blank = ['', ' ', '\t', ' \t ', '   '];

  it('is an error when signing', () => {
    for (const key of blank) {
      expect(() => signWebhookV1(key, v.timestamp, v.delivery_id, bodyOf(v))).toThrow('apiKey is required');
    }
    expect(signWebhookV1(v.api_key, v.timestamp, v.delivery_id, bodyOf(v))).toBe(v.signature);
  });

  it('is a refusal when verifying', () => {
    for (const key of blank) {
      expect(() => verifyWebhook(key, bodyOf(v), headerRecord(v), atNow(v))).toThrow(CryptoChiefError);
      expect(() => parseWebhookEvent(key, bodyOf(v), headerRecord(v), atNow(v))).toThrow(CryptoChiefError);
      expect(() => createWebhookHandler(key, () => {})).toThrow(CryptoChiefError);
    }
    expect(() => verifyWebhook(v.api_key, bodyOf(v), headerRecord(v), atNow(v))).not.toThrow();
  });
});

// A webhook as the platform sends it: raw JSON bytes and the three headers.
const KEY = 'test_api_key_123';
const TS = 1_789_430_400;
const DELIVERY = '44444444-4444-4444-8444-444444444444';
const AT = { now: new Date(TS * 1000) };

function signed(body: unknown): { raw: string; headers: Record<string, string> } {
  const raw = JSON.stringify(body);
  return {
    raw,
    headers: {
      [WEBHOOK_HEADERS.timestamp]: String(TS),
      [WEBHOOK_HEADERS.delivery]: DELIVERY,
      [WEBHOOK_HEADERS.signature]: signWebhookV1(KEY, TS, DELIVERY, raw),
    },
  };
}

describe('parseWebhookEvent', () => {
  it('returns the camelCased typed event, nulls kept', () => {
    const v = vector('payin_invoice_paid_with_nulls');
    const evt = parseWebhookEvent<PayInWebhookEvent & Record<string, unknown>>(v.api_key, bodyOf(v), headerRecord(v), atNow(v));
    const wire = JSON.parse(v.body!) as Record<string, unknown>;
    expect(evt.event).toBe(wire.event);
    expect(evt.orderId).toBe(wire.order_id);
    for (const [k, x] of Object.entries(wire)) {
      if (x === null) expect(evt[k.replace(/_([a-z])/g, (_m, c: string) => c.toUpperCase())]).toBeNull();
    }
  });

  it('throws WebhookVerificationError with the reason', () => {
    const { raw, headers } = signed({ event: 'payout.paid', uuid: 'p-1' });
    const err = (() => {
      try {
        parseWebhookEvent(KEY, raw.replace('p-1', 'p-2'), headers, AT);
      } catch (e) {
        return e;
      }
    })();
    expect(err).toBeInstanceOf(WebhookVerificationError);
    expect(err).toBeInstanceOf(CryptoChiefError);
    expect((err as WebhookVerificationError).reason).toBe('signature');
    expect((err as WebhookVerificationError).name).toBe('WebhookVerificationError');
  });

  it('throws CryptoChiefError on a signed body that is not JSON', () => {
    const raw = 'not json';
    const headers = { ...signed(null).headers, [WEBHOOK_HEADERS.signature]: signWebhookV1(KEY, TS, DELIVERY, raw) };
    expect(() => parseWebhookEvent(KEY, raw, headers, AT)).toThrow('webhook body is not JSON');
  });

  it('parses a body nested 10000 levels', () => {
    const raw = '{"a":'.repeat(9999) + '{}' + '}'.repeat(9999);
    const headers = { ...signed(null).headers, [WEBHOOK_HEADERS.signature]: signWebhookV1(KEY, TS, DELIVERY, raw) };
    let evt = parseWebhookEvent<Record<string, unknown>>(KEY, raw, headers, AT);
    let depth = 1;
    while (evt.a !== undefined) {
      evt = evt.a as Record<string, unknown>;
      depth++;
    }
    expect(depth).toBe(10000);
  });
});

describe('confirmation counts on webhook payloads', () => {
  it('types the payout counts per source, per service operation and overall', () => {
    const { raw, headers } = signed({
      event: 'payout.paid',
      uuid: 'p-1',
      order_id: 'o-1',
      status: 'paid',
      sources: [
        { address: '0xa', network: 'ETH_MAINNET', coin: 'USDT', amount_crypto: '100', txid: '0xaaa', confirmations: 40 },
        { address: '0xb', network: 'ETH_MAINNET', coin: 'USDT', amount_crypto: '50', txid: '0xbbb', confirmations: 33 },
      ],
      service_operations: [
        { type: 'gas_refuel', context: 'payout_prepare', status: 'done', txid: '0xgas', confirmations: 40 },
      ],
      confirmations: 33,
      required_confirmations: 32,
    });

    const evt = parseWebhookEvent<PayoutWebhookEvent>(KEY, raw, headers, AT);

    expect(evt.confirmations).toBe(33);
    // payout.paid is sent only once every source reached the depth.
    expect(evt.requiredConfirmations).toBe(32);
    expect(evt.sources?.every((s) => (s.confirmations ?? 0) >= evt.requiredConfirmations!)).toBe(true);
    expect(evt.sources?.map((s) => s.confirmations)).toEqual([40, 33]);
    expect(evt.sources?.[0]?.amountCrypto).toBe('100');
    expect(evt.sources?.[0]?.txid).toBe('0xaaa');
    expect(evt.sources?.[0]?.network).toBe('ETH_MAINNET');
    // The API never sends `amount`; the source amount is `amountCrypto`.
    expect(evt.sources?.[0]?.amount).toBeUndefined();
    expect(evt.sources?.reduce((sum, s) => sum + Number(s.amountCrypto), 0)).toBe(150);
    expect(evt.serviceOperations?.[0]?.confirmations).toBe(40);
  });

  it('leaves the payout counts absent when no source ever sent a transaction', () => {
    const { raw, headers } = signed({
      event: 'payout.system_fail',
      uuid: 'p-2',
      order_id: 'o-2',
      status: 'system_fail',
      sources: [{ address: '0xa', network: 'ETH_MAINNET', coin: 'USDT', amount_crypto: '10' }],
      service_operations: [],
      error_reason: 'no route',
    });

    const evt = parseWebhookEvent<PayoutWebhookEvent>(KEY, raw, headers, AT);

    expect(evt.confirmations).toBeUndefined();
    expect(evt.sources?.[0]?.confirmations).toBeUndefined();
    expect(evt.sources?.[0]?.amountCrypto).toBe('10');
    expect(evt.sources?.[0]?.txid).toBeUndefined();
    expect(evt.serviceOperations).toEqual([]);
    // A payout that never reached the confirmation step may carry no depth.
    expect(evt.requiredConfirmations).toBeUndefined();
    expect('requiredConfirmations' in evt).toBe(false);
  });

  it('types the transaction count and threshold, 0 included', () => {
    const confirmed = signed({
      event: 'transaction.confirmed',
      uuid: 't-1',
      status: 'confirmed',
      confirmations: 12,
      required_confirmations: 12,
    });
    const expired = signed({
      event: 'transaction.expired',
      uuid: 't-2',
      status: 'expired',
      confirmations: 0,
      required_confirmations: 20,
    });

    const ok = parseWebhookEvent<TransactionWebhookEvent>(KEY, confirmed.raw, confirmed.headers, AT);
    const gone = parseWebhookEvent<TransactionWebhookEvent>(KEY, expired.raw, expired.headers, AT);

    expect([ok.confirmations, ok.requiredConfirmations]).toEqual([12, 12]);
    expect([gone.confirmations, gone.requiredConfirmations]).toEqual([0, 20]);
  });
});

describe('sweep.confirmed payload', () => {
  const base = {
    event: 'sweep.confirmed',
    task_id: 'task-1',
    status: 'completed',
    wallet_address: 'TQrY8bYc2yQ8sM8nJ1sZ9c2Zx7L2wq7pQb',
    to_address: 'TMaster1111111111111111111111111111',
    network: 'TRON_MAINNET',
    chain_family: 'TRON',
    asset_symbol: 'USDT',
    asset_type: 'token',
    amount_human: '125.5',
    sweep_tx_hash: 'abc123',
    confirmed_at: '2026-09-14T10:00:00Z',
  };

  it('carries the depth the sweep was held to, reached by the count', () => {
    const { raw, headers } = signed({ ...base, sweep_confirmations: 21, required_confirmations: 20 });

    const evt = parseWebhookEvent<SweepWebhookEvent>(KEY, raw, headers, AT);

    expect(evt.sweepConfirmations).toBe(21);
    expect(evt.requiredConfirmations).toBe(20);
    expect(evt.sweepConfirmations).toBeGreaterThanOrEqual(evt.requiredConfirmations!);
  });

  it('parses an event from a sweep service that predates the depth', () => {
    const { raw, headers } = signed({ ...base, sweep_confirmations: 1 });

    const evt = parseWebhookEvent<SweepWebhookEvent>(KEY, raw, headers, AT);

    expect(evt.taskId).toBe('task-1');
    expect(evt.sweepConfirmations).toBe(1);
    expect(evt.requiredConfirmations).toBeUndefined();
    expect('requiredConfirmations' in evt).toBe(false);
  });
});

describe('createWebhookHandler over HTTP', () => {
  interface Sent {
    status: number;
    text: string;
  }

  function post(
    port: number,
    body: Buffer | string,
    headers: Record<string, string | string[]>,
    method = 'POST',
    agent?: Agent,
  ): Promise<Sent> {
    return new Promise((resolve, reject) => {
      const req = request({ host: '127.0.0.1', port, method, path: '/webhook', headers, agent }, (res) => {
        const chunks: Buffer[] = [];
        res.on('data', (c: Buffer) => chunks.push(c));
        res.on('end', () => resolve({ status: res.statusCode ?? 0, text: Buffer.concat(chunks).toString('utf8') }));
      });
      req.on('error', reject);
      req.end(body);
    });
  }

  async function withServer<T>(
    handler: Parameters<typeof createServer>[1],
    run: (port: number) => Promise<T>,
  ): Promise<T> {
    const server: Server = createServer(handler);
    await new Promise<void>((resolve) => server.listen(0, '127.0.0.1', resolve));
    try {
      return await run((server.address() as AddressInfo).port);
    } finally {
      await new Promise<void>((resolve) => server.close(() => resolve()));
    }
  }

  it('verifies the raw body and headers, and answers 401 for each reason', async () => {
    const events: { event: string; delivery: string | undefined; headers: IncomingHttpHeaders }[] = [];
    const v = vector('payin_invoice_paid_with_nulls');
    const body = bodyOf(v);
    const good = { 'Content-Type': 'application/json', ...headerRecord(v) } as Record<string, string>;

    await withServer(
      createWebhookHandler<PayInWebhookEvent>(
        v.api_key,
        (evt, { req }) => {
          events.push({ event: evt.event, delivery: req.headers['x-webhook-delivery'] as string, headers: req.headers });
        },
        { now: () => new Date(v.now * 1000) },
      ),
      async (port) => {
        expect(await post(port, body, good)).toEqual({ status: 200, text: '' });

        const badSig = await post(port, body, { ...good, 'X-CC-Signature': 'v1=' + '0'.repeat(64) });
        expect(badSig).toEqual({ status: 401, text: 'cryptochief: webhook signature does not match' });

        const changed = Buffer.from(body);
        changed[10] = changed[10]! ^ 1;
        expect((await post(port, changed, good)).status).toBe(401);

        const stale = await post(port, body, { ...good, 'X-CC-Timestamp': String(v.now - 301) });
        expect(stale).toEqual({ status: 401, text: 'cryptochief: webhook timestamp is out of range' });

        const repeated = await post(port, body, { ...good, 'X-CC-Signature': [v.signature, v.signature] });
        expect(repeated).toEqual({
          status: 401,
          text: 'cryptochief: webhook signature headers are missing, repeated or malformed',
        });

        const legacy = { 'Content-Type': 'application/json', Signature: v.signature.slice(3), 'X-Webhook-Signature': v.signature.slice(3) };
        expect((await post(port, body, legacy)).status).toBe(401);

        expect((await post(port, body, good, 'GET')).status).toBe(405);
      },
    );

    expect(events).toHaveLength(1);
    expect(events[0]!.event).toBe('invoice.paid');
    expect(events[0]!.delivery).toBe(v.delivery_id);
  });

  it('verifies a non-UTF-8 body, then answers 400 because it is not JSON', async () => {
    const v = vector('body_not_utf8');
    let called = false;
    await withServer(
      createWebhookHandler(v.api_key, () => {
        called = true;
      }, { now: new Date(v.now * 1000) }),
      async (port) => {
        const res = await post(port, bodyOf(v), headerRecord(v) as Record<string, string>);
        expect(res).toEqual({ status: 400, text: 'cryptochief: webhook body is not JSON' });
      },
    );
    expect(called).toBe(false);
  });

  it('uses the system clock by default', async () => {
    const raw = JSON.stringify({ event: 'transaction.confirmed', uuid: 't-1', status: 'confirmed' });
    const ts = Math.floor(Date.now() / 1000);
    const seen: string[] = [];
    await withServer(
      createWebhookHandler<TransactionWebhookEvent>(KEY, (evt, { res }) => {
        seen.push(evt.uuid);
        res.writeHead(202).end('accepted');
      }),
      async (port) => {
        const res = await post(port, raw, {
          'Content-Type': 'application/json',
          'X-CC-Timestamp': String(ts),
          'X-Webhook-Delivery': DELIVERY,
          'X-CC-Signature': signWebhookV1(KEY, ts, DELIVERY, raw),
        });
        expect(res).toEqual({ status: 202, text: 'accepted' });
        const old = await post(port, raw, {
          'X-CC-Timestamp': String(TS),
          'X-Webhook-Delivery': DELIVERY,
          'X-CC-Signature': signWebhookV1(KEY, TS, DELIVERY, raw),
        });
        expect(old.status).toBe(401);
      },
    );
    expect(seen).toEqual(['t-1']);
  });

  it('answers 413 to a body over maxBodyBytes and keeps the connection', async () => {
    const v = vector('payin_invoice_paid_with_nulls');
    const body = bodyOf(v);
    const headers = { 'Content-Type': 'application/json', ...headerRecord(v) } as Record<string, string>;
    const events: string[] = [];
    const server: Server = createServer(
      createWebhookHandler<PayInWebhookEvent>(v.api_key, (evt) => {
        events.push(evt.event);
      }, { now: new Date(v.now * 1000), maxBodyBytes: body.length }),
    );
    let connections = 0;
    server.on('connection', () => connections++);
    await new Promise<void>((resolve) => server.listen(0, '127.0.0.1', resolve));
    const port = (server.address() as AddressInfo).port;
    const agent = new Agent({ keepAlive: true, maxSockets: 1 });
    const tooLarge = { status: 413, text: 'cryptochief: webhook body too large' };
    try {
      expect(await post(port, Buffer.concat([body, Buffer.from(' ')]), headers, 'POST', agent)).toEqual(tooLarge);
      expect(await post(port, Buffer.alloc(300_000, 0x61), headers, 'POST', agent)).toEqual(tooLarge);
      expect(await post(port, body, headers, 'POST', agent)).toEqual({ status: 200, text: '' });
    } finally {
      agent.destroy();
      await new Promise<void>((resolve) => server.close(() => resolve()));
    }
    expect(connections).toBe(1);
    expect(events).toEqual(['invoice.paid']);
  });

  it('answers 413 with Connection: close and closes once 1 MiB past maxBodyBytes is read', async () => {
    const limit = 1024;
    let called = false;
    const response = await withServer(
      createWebhookHandler(KEY, () => {
        called = true;
      }, { maxBodyBytes: limit }),
      (port) =>
        new Promise<string>((resolve, reject) => {
          const socket = connect(port, '127.0.0.1');
          const chunks: Buffer[] = [];
          socket.on('data', (c: Buffer) => chunks.push(c));
          socket.on('error', reject);
          socket.on('close', () => resolve(Buffer.concat(chunks).toString('latin1')));
          socket.write(`POST /webhook HTTP/1.1\r\nHost: 127.0.0.1\r\nContent-Length: ${8 << 20}\r\n\r\n`);
          socket.write(Buffer.alloc(limit + (1 << 20) + 1, 0x61));
        }),
    );
    expect(response.startsWith('HTTP/1.1 413 ')).toBe(true);
    expect(response).toMatch(/\r\nConnection: close\r\n/i);
    expect(response.slice(response.indexOf('\r\n\r\n'))).toContain('cryptochief: webhook body too large');
    expect(called).toBe(false);
  });

  it('rejects an empty apiKey when created', () => {
    expect(() => createWebhookHandler('', () => undefined)).toThrow(CryptoChiefError);
  });
});
